export const URLS = {
  refreshToken: '/api/Auth/RefreshToken',
  login: 'api/Auth/Login',
  logout: '/api/Auth/Logout',
  addTrustedDevice: '/api/Auth/AddTrustedDevice',
  getTrustedDevices: '/api/Auth/GetTrustedDevices',
  getTemplates: 'api/Templates/GetTemplates',
  getUserProfile: 'api/Customers/GetUserProfile',
  loginByRefreshToken: '/api/Auth/LoginByRefreshToken',
  getCreditCard: 'api/Loan/GetCreditCard',
  getOverdraft: 'api/Loan/GetOverDraft',
  getLoanCustomerId: 'api/Loan/GetLoanByCustomerId',
  getCustomperOps: 'api/Transaction/GetCustomerOps',
  getAssets: 'api/Deposit/GetDepositByClientId',
  getPensions: 'api/Pensions/GetTotalSaving',
  getBankerInfo: 'api/Customers/GetBankerInfo',
  getAccountsByCustomerId: 'api/Account/GetAccountsByCustomerId',
  getOffers: 'api/Offers/GetOffers',
  getDepositsByClientId: 'api/Deposit/GetDepositByClientId',
  getLoansByCustomerId: 'api/Loan/GetLoanByCustomerId',
};
